### ISSUE TITLE
Is the full 30.00 package indeed on backorder?  How long of a wait is estimated?

### ISSUE THREAD

**Issue by zettalion** [PaulWieland/ratgdo#44]
I have been following this thread for a few months and was hoping for ESPHOME integration as well.  I decided to stop waiting - and was about to purchase the full 30.00 shield and it claims it is on Backorder.   Is this just because the designer has to "build up" the board before shipping, and the customer has to expect to wait a couple of days before shipping?   

Or is it indeed on backorder and I might have to wait a few months for it to arrive?

Any insight from someone who has recently ordered or feedback from the site owner would be appreciated. 

Thanks for all you do !

**Comment by PaulWieland** [comment]
It’s backordered when I do not have any stock to ship out. It’s been hard for me to gauge how many to stock, and demand keeps increasing so I haven’t caught up yet.

I’m having an issue with the next order due to shortage of screw terminals, but should hopefully have them ready to ship out in 3-4 weeks.
