### ISSUE TITLE
Question - Solder-Free Connection to Rotary Encoder?

### ISSUE THREAD

**Issue by maniacaris** [PaulWieland/ratgdo#6]
Hi Paul,

Per your advice I bought a replacement rotary encoder and plan to swap them out sometime this week. In looking at it, I noticed the connector has silkscreened labels for VCC, GND, RPM1, and RPM2 along with a few others. It got me thinking about whether I could make up a custom cable with the same JST/XH connector and tap directly off the cable instead of soldering to the board. That would obviously depend on the operating voltage of the encoder, but it could make for much less invasive and more reliable installation. Just wondering if you poked around on the encoder side at all and, if so, whether you thought it would work. If not, I'd be happy to try it out and get back to you.

**Comment by PaulWieland** [comment]
I thought about this when designing it. Problem is finding a female connector for a cable as typically the female part is a socket on a board. 

The second problem is that you have to solder the 3.3v pin anyway because the 3.3v supplied to the encoder cannot provide enough current to power the esp8266.
