### ISSUE TITLE
Door always shows open. Close button closes and opens. 

### ISSUE THREAD

**Issue by sco0ts** [PaulWieland/ratgdo#99]
Just hooked up the ratgdo. Showing door state as always open. Showing light as always on. 

Down action makes the door close and open. 

Stop action does nothing. 

Installed on a Chamberlain B2202

**Comment by sco0ts** [comment]
![IMG_3487](https://github.com/PaulWieland/ratgdo/assets/36104678/6ef952ef-162b-434d-97be-83d086f7ed8b)
![IMG_3486](https://github.com/PaulWieland/ratgdo/assets/36104678/37aeab33-f509-4f75-aebd-b9e5d370f40a)

**Comment by PaulWieland** [comment]
What’s your order number?

**Comment by sco0ts** [comment]
*11ee5229778b9fc593a3ac1f6bbba828*

**Comment by PaulWieland** [comment]
Sorry that’s not it. It would be on your receipt sent by square. I can also check by email address.

**Comment by sco0ts** [comment]
The issue is with the item from my most recent order. I cannot find that
order number. This is the order number from a previous order if you are
able to look up my other orders
2033347675

**Comment by PaulWieland** [comment]
I found it. Will send you a replacement as soon as possible.

**Comment by PaulWieland** [comment]
Email sent

**Comment by barthjp** [comment]
I'm having a similar issue. It looks like I'm not seeing any status updates on the door or light. The only status updates I'm getting are the availability and obstruction. Can you comment on how this issue was resolved?
![mqtt-no-door-status](https://github.com/PaulWieland/ratgdo/assets/4183594/a9e61f4d-5d85-4323-86eb-5f6e9845e6eb)

Order# 11ee5af182dd9a8893a3ac1f6bbba828
